# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/main/.rubocop.yml

AllCops:
  TargetRubyVersion: 3.0

Layout/LineLength:
  Exclude:
    - Gemfile
