module Hanami
  module Lambda
    # Base event class
    #
    # @since 0.2.0
    class Event
      @raw: untyped

      @event: untyped

      attr_reader raw: untyped

      # @param event [Hash] the raw event from AWS Lambda
      # @return [Hanami::Lambda::Event]
      #
      # @since 0.2.0
      def initialize: (untyped event) -> void

      # Return the value of the given key
      #
      # @param key [Symbol] the key to fetch
      #
      # @return [Object,NilClass] the associated value if found
      #
      # @since 0.2.0
      def []: (untyped key) -> untyped

      # Return an value associated with the given event key
      #
      # @param keys [Array<Symbol, Integer>] the keys to fetch
      #
      # @return [Object,NilClass] the associated value if found
      #
      # @since 0.2.0
      def get: (*untyped keys) -> untyped

      alias dig get

      # Return the hash of the event
      #
      # @return [Hash] the hash of the event
      #
      # @since 0.2.0
      def to_h: () -> untyped
    end
  end
end
