name: CI

on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - 'lib/**'
      - 'sig/**'
      - '*.gemspec'
      - 'spec/**'
      - 'Rakefile'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'Steepfile'
      - 'rbs_collection.lock.yaml'
      - '.rubocop.yml'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 4 * * *'
  create:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '4.0'
          - '3.4'
          - '3.3'
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Set up Ruby
      uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Bootstrap RBS
      run: bundle exec rbs collection install
    - name: Run all tests
      run: bundle exec rake
