name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'lib/**'
      - '*.gemspec'
      - 'spec/**'
      - 'Rakefile'
      - 'Gemfile'
      - '.rubocop.yml'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 4 * * *'
  create:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.1'
          - '3.0'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Bootstrap RBS
      run: rbs collection install
    - name: Run all tests
      run: bundle exec rake
